name: Check website every 2 hours

on:
  pull_request:
    types:
      - opened
      - synchronize

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFICATIONS_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1

      - name: Run Cypress Workflow
        uses: ./cypress.yml

      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              
              "Repository": "github.com/internxt/website.git",
              "Platform": "Web",
              "Description": "${{github.job.status}}",
            }
