name: Pre build

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create .env.local
        run: echo '${{ secrets.ENV_LOCAL }}' > .env.local

      - name: Verify .env.local (for debugging)
        run: cat .env.local

      - name: Load environment variables
        run: source .env.local

      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
